### PR TITLE
Database class added

### PR DESCRIPTION
**Pull request by christopher-weber**
For each contact person a .db file will be created and named with the hash value of the contact persons public key. Each file contains one line per encounter to an infected person.

### CODE REVIEW

**Comment by kuhlmannmarkus** [comment]
Top! Ich teste morgen.

**Comment by kuhlmannmarkus** [comment]
Kannst Du Dich darum noch kümmern. Ansonsten bin ich mit dem Design höchst zufrieden. Good job!

db/db.h:26:65: error: 'UINT64' was not declared in this scope
   std::vector<std::tuple<std::string,std::string,double,double, UINT64>>  getEncounters(std::string puplicKeyContactPerson);

db/db.cpp:15:74: error: template argument 2 is invalid
db/db.cpp:17:10: error: request for member 'clear' in 'result', which is of non-class type 'int'
   result.clear();

db/db.cpp:81:40: error: request for member 'at' in '_encounters', which is of non-class type 'int'
     outfile << std::get<0>(_encounters.at(i));

db/db.cpp: In member function 'std::vector<std::__cxx11::basic_string<char> > DB::splitString(std::__cxx11::string, std::__cxx11::string)':
db/db.cpp:107:72: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while ((endIndex = _stringToBeSplitted.find(_delimeter, startIndex)) < _stringToBeSplitted.size())

**Comment by christopher-weber** [comment]
Hallo Martin, Mach ich sobald ich zu Hause bin!Danke! Meld dich falls ihr noch offene Tasks habt! Grüße Christopher -- Am 23.03.20, 09:45 schrieb Markus Kuhlmann <notifications@github.com>:

   
  Kannst Du Dich darum noch kümmern. Ansonsten bin ich mit dem Design höchst zufrieden. Good job! 
  db/db.h:26:65: error: 'UINT64' was not declared in this scope std::vector<std::tuple<std::string,std::string,double,double, UINT64>> getEncounters(std::string puplicKeyContactPerson); 
  db/db.cpp:15:74: error: template argument 2 is invalid db/db.cpp:17:10: error: request for member 'clear' in 'result', which is of non-class type 'int' result.clear(); 
  db/db.cpp:81:40: error: request for member 'at' in '_encounters', which is of non-class type 'int' outfile << std::get<0>(_encounters.at(i)); 
  db/db.cpp: In member function 'std::vector<std::__cxx11::basic_string > DB::splitString(std::__cxx11::string, std::__cxx11::string)': db/db.cpp:107:72: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] while ((endIndex = _stringToBeSplitted.find(_delimeter, startIndex)) < _stringToBeSplitted.size())

**Comment by christopher-weber** [comment]
@kuhlmannmarkus I've resolved your findings.

**Pull request merged**
